// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'person.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Person _$PersonFromJson(Map json) => Person(
  uid: json['uid'] as String?,
  profilePhoto: json['profilePhoto'] as String?,
  email: json['email'] as String?,
  name: json['name'] as String?,
  age: (json['age'] as num?)?.toInt(),
  phoneNumber: json['phoneNumber'] as String?,
  gender: json['gender'] as String?,
  orientation: json['orientation'] as String?,
  username: json['username'] as String?,
  country: json['country'] as String?,
  province: json['province'] as String?,
  city: json['city'] as String?,
  relationshipStatus: json['relationshipStatus'] as String?,
  lookingForBreakfast: json['lookingForBreakfast'] as bool?,
  lookingForLunch: json['lookingForLunch'] as bool?,
  lookingForDinner: json['lookingForDinner'] as bool?,
  lookingForLongTerm: json['lookingForLongTerm'] as bool?,
  publishedDateTime: (json['publishedDateTime'] as num?)?.toInt(),
  height: json['height'] as String?,
  bodyType: json['bodyType'] as String?,
  drinkSelection: json['drinkSelection'] as bool?,
  smokeSelection: json['smokeSelection'] as bool?,
  meatSelection: json['meatSelection'] as bool?,
  greekSelection: json['greekSelection'] as bool?,
  hostSelection: json['hostSelection'] as bool?,
  travelSelection: json['travelSelection'] as bool?,
  profession: json['profession'] as String?,
  income: json['income'] as String?,
  professionalVenues: (json['professionalVenues'] as List<dynamic>?)
      ?.map((e) => e as String)
      .toList(),
  otherProfessionalVenue: json['otherProfessionalVenue'] as String?,
  ethnicity: json['ethnicity'] as String?,
  nationality: json['nationality'] as String?,
  languages: json['languages'] as String?,
  instagram: json['instagram'] as String?,
  twitter: json['twitter'] as String?,
  urlImage1: json['urlImage1'] as String?,
  urlImage2: json['urlImage2'] as String?,
  urlImage3: json['urlImage3'] as String?,
  urlImage4: json['urlImage4'] as String?,
  urlImage5: json['urlImage5'] as String?,
);

Map<String, dynamic> _$PersonToJson(Person instance) => <String, dynamic>{
  'uid': instance.uid,
  'profilePhoto': instance.profilePhoto,
  'email': instance.email,
  'name': instance.name,
  'age': instance.age,
  'phoneNumber': instance.phoneNumber,
  'gender': instance.gender,
  'orientation': instance.orientation,
  'username': instance.username,
  'country': instance.country,
  'province': instance.province,
  'city': instance.city,
  'relationshipStatus': instance.relationshipStatus,
  'lookingForBreakfast': instance.lookingForBreakfast,
  'lookingForLunch': instance.lookingForLunch,
  'lookingForDinner': instance.lookingForDinner,
  'lookingForLongTerm': instance.lookingForLongTerm,
  'publishedDateTime': instance.publishedDateTime,
  'height': instance.height,
  'bodyType': instance.bodyType,
  'drinkSelection': instance.drinkSelection,
  'smokeSelection': instance.smokeSelection,
  'meatSelection': instance.meatSelection,
  'greekSelection': instance.greekSelection,
  'hostSelection': instance.hostSelection,
  'travelSelection': instance.travelSelection,
  'profession': instance.profession,
  'income': instance.income,
  'professionalVenues': instance.professionalVenues,
  'otherProfessionalVenue': instance.otherProfessionalVenue,
  'ethnicity': instance.ethnicity,
  'nationality': instance.nationality,
  'languages': instance.languages,
  'instagram': instance.instagram,
  'twitter': instance.twitter,
  'urlImage1': instance.urlImage1,
  'urlImage2': instance.urlImage2,
  'urlImage3': instance.urlImage3,
  'urlImage4': instance.urlImage4,
  'urlImage5': instance.urlImage5,
};
