// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0limZkm4u8KRp-qCnKLX8l1N7HvVeBQ',
    appId: '1:884472216905:web:21026ec4ef01278436ae98',
    messagingSenderId: '884472216905',
    projectId: 'eavzappl-32891',
    authDomain: 'eavzappl-32891.firebaseapp.com',
    storageBucket: 'eavzappl-32891.firebasestorage.app',
    measurementId: 'G-FP2ZLTCB9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAosamV_fIIIMiUNSt2Mgdk3gc2vPB_-6Y',
    appId: '1:884472216905:android:61cb5724cb5bba0136ae98',
    messagingSenderId: '884472216905',
    projectId: 'eavzappl-32891',
    storageBucket: 'eavzappl-32891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vYWwVY__tqLeiPAOoVt7l_G5_pjyLmY',
    appId: '1:884472216905:ios:ffd91bbd5e65670f36ae98',
    messagingSenderId: '884472216905',
    projectId: 'eavzappl-32891',
    storageBucket: 'eavzappl-32891.firebasestorage.app',
    iosBundleId: 'com.blerdguild.eavzappl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8vYWwVY__tqLeiPAOoVt7l_G5_pjyLmY',
    appId: '1:884472216905:ios:ffd91bbd5e65670f36ae98',
    messagingSenderId: '884472216905',
    projectId: 'eavzappl-32891',
    storageBucket: 'eavzappl-32891.firebasestorage.app',
    iosBundleId: 'com.blerdguild.eavzappl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz0limZkm4u8KRp-qCnKLX8l1N7HvVeBQ',
    appId: '1:884472216905:web:077657d26a1682b136ae98',
    messagingSenderId: '884472216905',
    projectId: 'eavzappl-32891',
    authDomain: 'eavzappl-32891.firebaseapp.com',
    storageBucket: 'eavzappl-32891.firebasestorage.app',
    measurementId: 'G-Y92WM20X8X',
  );
}
